#!/bin/sh

set -e

cd "${WORKDIR}"
source .env

cd "${TARGET_DIR}"

[ ! -f "go.mod" ] && go mod init function

echo "${FUNCTION_SPEC}" > openapi-spec.json

cat <<EOF > generate.go
package project

//go:generate go run github.com/ogen-go/ogen/cmd/ogen@latest --target api --clean openapi-spec.json
EOF

go generate ./...

fngogen --spec openapi-spec.json

go mod tidy
go vet ./... 2>&1 | grep -v "generated by" || true
go fmt ./...

tree .