#!/bin/sh

set -e

cd "${WORKDIR}"
source .env

cd "${TARGET_DIR}"

# API_IMPORT_PATH (kdex-tech/fngogen#11) places the head inside an existing
# module: it names that module's import path for TARGET_DIR/api, so no nested
# `module function` is created.
[ -z "${API_IMPORT_PATH}" ] && [ ! -f "go.mod" ] && go mod init function

echo "${FUNCTION_API_SPEC}" > openapi-spec.json

# Route text/event-stream responses to ogen's RawHandler (kdex-tech/fngogen#9).
fngogen --prepare --spec openapi-spec.json

cat <<EOF > generate.go
package project

//go:generate go run github.com/ogen-go/ogen/cmd/ogen@latest --target api --clean openapi-spec.json
EOF

go generate ./...

fngogen --spec openapi-spec.json ${API_IMPORT_PATH:+-api-import "$API_IMPORT_PATH"}

go mod tidy
go vet ./... 2>&1 | grep -v "generated by" || true
go fmt ./...

cat <<EOF > project.toml
[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "BP_GO_TARGETS"
value = "./cmd/"
EOF

tree .