#!/bin/sh

set -e

cd "${WORKDIR}"
source .env

cd "${TARGET_DIR}"

[ ! -f "go.mod" ] && go mod init function

echo "${FUNCTION_API_SPEC}" > openapi-spec.json

cat <<EOF > generate.go
package project

//go:generate go run github.com/ogen-go/ogen/cmd/ogen@latest --target api --clean openapi-spec.json
EOF

go generate ./...

fngogen --spec openapi-spec.json

go mod tidy
go vet ./... 2>&1 | grep -v "generated by" || true
go fmt ./...

cat <<EOF > project.toml
[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "BP_GO_TARGETS"
value = "./cmd/"
EOF

tree .